### ISSUE TITLE
BTS Pro Series Season 9

### ISSUE THREAD

**Issue by RefreshJunior** [datdota/datdota#39]
Hello! Any problem with the data of BTS Pro Series Season 9? It seems that matches after 10/30/2021 are not loading

**Comment by Noxville** [comment]
Was mistakenly marked as amateur so didn't load. Fixed that, matches pulled in - they all should be parsed in 10-15 mins time.

**Comment by RefreshJunior** [comment]
Thanks boss! You are really incredible

**Comment by RefreshJunior** [comment]
However, the draft summary still only contains 9 league matches 13499

**Comment by Noxville** [comment]
You probably should be using league_id 13659: http://datdota.com/drafts?faction=both&first-pick=either&leagues=13659&tier=1&tier=2&valve-event=does-not-matter&patch=7.30&after=01%2F01%2F2011&before=06%2F11%2F2021&duration=0%3B200&duration-value-from=0&duration-value-to=200

One of the matches didn't have a draft (you can tell because http://datdota.com/match-durations?leagues=13659&tier=1&tier=2&valve-event=does-not-matter&patch=7.30&after=01%2F01%2F2011&before=06%2F11%2F2021&duration=0%3B200&duration-value-from=0&duration-value-to=200 has one more game)

**Comment by RefreshJunior** [comment]
again thank you
