### ISSUE TITLE
Drafts pick counts discrepancy

### ISSUE THREAD

**Issue by howardchung** [datdota/datdota#6]
On page:
http://datdota.com/drafts?faction=both&first-pick=either&teams=111474&tier=1&tier=2&valve-event=does-not-matter&patch=7.04&patch=7.03&patch=7.02&patch=7.01&patch=7.00&patch=6.88&patch=6.87&patch=6.86&patch=6.85&patch=6.84&patch=6.83&patch=6.82&patch=6.81&patch=6.80&patch=6.79&patch=6.78&patch=6.77&patch=6.76&patch=6.75&patch=6.74&winner=either&after=01%2F01%2F2011&before=02%2F04%2F2017&duration=0%3B200

I summed the picks column and got 11830.  The number of matches according to the text above the table is 1186.  This is a difference of 30, which is probably due to some matches missing draft data.

However, shouldn't the sum of picks be half that (5 picks per match?).  I'm guessing the query for this page is including the picks of the other team as well?

**Comment by howardchung** [comment]
I just noticed that the "both factions" option was selected.  However, since I applied a team filter, shouldn't the table return the data for the selected team?

**Comment by Noxville** [comment]
There are like 3 games without drafts (remake -ap).

'Drafts' are an interaction between two teams. The teams filter (which says 'at least one must appear') are exactly that - finding games involving at least one of the specified teams. 

This is because looking only at a single team's picks/bans are often misleading. A team might have a preference for picking A > B > C, but since A and B are always banned in games involving them (by the enemy, or by themself if they don't have first pick) they might pick mostly C. Another issue is that if there are certain heroes which are "OP", it's often arbitrary which of the two teams in a game ban the hero (if one doesn't the other will). This leads you to seeing the frequency table of heroes picked without any context of their preferences. The drafts page allow an undistorted view of this.

A potential solution would be to do a breakdown of Team A vs Team B vs Team C ... vs {their collective opponents}, but this fails if many of the games are actually between the specified teams.

The better alternative in my eyes is showing the picks of a team as one statistic (represented in Hero (Elo) Performance) for picks, and another view for Bans (coming sometime) which breaks down the bans in games involving a team, and looking at what %  they ban vs their opponent (> 50% with a large sample would be the interesting cases).

**Comment by howardchung** [comment]
Makes sense.  Thanks for the explanation!
